//go:build ignore

// Command gen_zones writes zones.go: every IANA zone name the binary can load,
// grouped by region, for the time-zone picker on the settings page.
//
// The names come out of the Go toolchain's own zoneinfo.zip, which is the same
// database `time/tzdata` embeds, so the list cannot offer a zone the server
// would then refuse. CI regenerates it and fails on a difference, the way it
// does for the stylesheet and the configuration reference, and the toolchain
// version is pinned by go.mod, so the two agree by construction.
package main

import (
	"archive/zip"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
)

// regions are the prefixes a canonical zone name starts with. Everything else
// in the archive is a compatibility alias: single names such as EST and Zulu,
// the Etc/GMT+n set whose signs run the wrong way round, and the country trees
// (US/, Canada/, Brazil/) that IANA keeps only so old configurations load.
var regions = []string{
	"Africa", "America", "Antarctica", "Arctic", "Asia",
	"Atlantic", "Australia", "Europe", "Indian", "Pacific",
}

// denied are aliases that live inside a region tree, so the prefix rule alone
// does not catch them. Each names the same place as a city entry beside it.
var denied = map[string]bool{
	"Australia/ACT": true, "Australia/LHI": true, "Australia/NSW": true,
	"Australia/North": true, "Australia/Queensland": true, "Australia/South": true,
	"Australia/Tasmania": true, "Australia/Victoria": true, "Australia/West": true,
	"America/Godthab": true, "America/Buenos_Aires": true, "America/Catamarca": true,
	"America/Cordoba": true, "America/Jujuy": true, "America/Mendoza": true,
	"America/Rosario": true, "America/Knox_IN": true, "America/Indianapolis": true,
	"America/Fort_Wayne": true, "America/Louisville": true, "America/Montreal": true,
	"America/Porto_Acre": true, "America/Santa_Isabel": true, "America/Shiprock": true,
	"America/Virgin": true, "America/Ensenada": true, "America/Atka": true,
	"Asia/Ashkhabad": true, "Asia/Calcutta": true, "Asia/Chungking": true,
	"Asia/Dacca": true, "Asia/Harbin": true, "Asia/Istanbul": true, "Asia/Katmandu": true,
	"Asia/Macao": true, "Asia/Rangoon": true, "Asia/Saigon": true, "Asia/Tel_Aviv": true,
	"Asia/Thimbu": true, "Asia/Ujung_Pandang": true, "Asia/Ulan_Bator": true,
	"Africa/Asmera": true, "Africa/Timbuktu": true,
	"Atlantic/Faeroe": true, "Atlantic/Jan_Mayen": true,
	"Europe/Belfast": true, "Europe/Kiev": true, "Europe/Nicosia": true, "Europe/Tiraspol": true,
	"Pacific/Ponape": true, "Pacific/Samoa": true, "Pacific/Truk": true, "Pacific/Yap": true,
	"Pacific/Johnston": true, "Pacific/Enderbury": true,
	"Indian/Comoro": true, "Indian/Mayotte": true,
}

// main writes zones.go from the tzdata the toolchain ships, so the zone list on
// the settings page is the one the binary can actually load.
func main() {
	out, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		log.Fatalf("go env GOROOT: %v", err)
	}
	path := filepath.Join(strings.TrimSpace(string(out)), "lib", "time", "zoneinfo.zip")
	z, err := zip.OpenReader(path)
	if err != nil {
		log.Fatalf("open %s: %v", path, err)
	}
	defer func() { _ = z.Close() }()

	byRegion := map[string][]string{}
	for _, f := range z.File {
		name := f.Name
		if strings.HasSuffix(name, "/") || denied[name] {
			continue
		}
		region, _, ok := strings.Cut(name, "/")
		if !ok || !slices.Contains(regions, region) {
			continue
		}
		byRegion[region] = append(byRegion[region], name)
	}

	var b strings.Builder
	b.WriteString("// Code generated by gen_zones.go; DO NOT EDIT.\n\n")
	b.WriteString("package model\n\n")
	b.WriteString("// ZoneGroup is one region of the time-zone picker.\n")
	b.WriteString("type ZoneGroup struct {\n\tRegion string\n\tZones  []string\n}\n\n")
	b.WriteString("// zoneGroups is every IANA zone name this binary can load, by region.\n")
	b.WriteString("// Aliases are left out: one place, one name in the list.\n")
	b.WriteString("var zoneGroups = []ZoneGroup{\n")
	total := 0
	for _, region := range regions {
		names := byRegion[region]
		if len(names) == 0 {
			continue
		}
		slices.Sort(names)
		total += len(names)
		fmt.Fprintf(&b, "\t{Region: %q, Zones: []string{\n", region)
		for _, n := range names {
			fmt.Fprintf(&b, "\t\t%q,\n", n)
		}
		b.WriteString("\t}},\n")
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "// ZoneCount is how many names the picker offers, %d at the time of writing.\n", total)
	b.WriteString("const ZoneCount = ")
	fmt.Fprintf(&b, "%d\n", total)

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatalf("format: %v", err)
	}
	if err := os.WriteFile("zones.go", src, 0o600); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("zones.go: %d zones in %d regions\n", total, len(byRegion))
}
