// Package model holds the domain types shared by every layer. It imports
// nothing from this module so that store backends, the service layer and the
// front-ends can all depend on it without cycles.
package model

import "time"

// ID is an opaque identifier. IDs are generated by the service layer and are
// the same on every storage backend, which keeps snapshots portable.
type ID string

// Board owns columns, cards and labels.
type Board struct {
	ID        ID
	Slug      string // URL segment, unique; [a-z0-9]+(-[a-z0-9]+)*
	Name      string
	Columns   []Column // ordered by Position
	Labels    []Label  // ordered by Name
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Column returns the column with the given ID, or nil.
func (b *Board) Column(id ID) *Column {
	for i := range b.Columns {
		if b.Columns[i].ID == id {
			return &b.Columns[i]
		}
	}
	return nil
}

// Label returns the label with the given ID, or nil.
func (b *Board) Label(id ID) *Label {
	for i := range b.Labels {
		if b.Labels[i].ID == id {
			return &b.Labels[i]
		}
	}
	return nil
}

// Column is a lane on a board. Columns are data, not an enum.
type Column struct {
	ID       ID
	BoardID  ID
	Name     string
	Position int
	WIPLimit int // 0 = no limit
}

// Card is a task on a board, living in exactly one column.
type Card struct {
	ID          ID
	BoardID     ID
	ColumnID    ID
	Title       string
	Description string    // markdown
	Position    int       // order within the column; gaps are allowed
	DueDate     time.Time // zero = none; date only, kept at 00:00 UTC
	// Assignee is the address of whoever is on the card, empty for nobody.
	// It is stored as the identity provider gave it rather than as a foreign
	// key: the board has no user table, and people who log in once and never
	// again should not leave rows behind.
	Assignee string
	// ArchivedAt is when the card left the board, zero while it is on it.
	// Archiving is not deleting: the card keeps its column, position, labels
	// and subtasks, so putting it back is the same card and not a copy.
	ArchivedAt time.Time
	Labels     []ID      // label IDs, sorted
	Subtasks   []Subtask // ordered by Position
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Archived reports whether the card has left the board.
func (c Card) Archived() bool { return !c.ArchivedAt.IsZero() }

// Label is a per-board tag that can be attached to cards.
type Label struct {
	ID      ID
	BoardID ID
	Name    string
	Color   string // CSS colour; empty for the default
}

// Subtask is one checklist item on a card.
type Subtask struct {
	ID       ID
	Title    string
	Done     bool
	Position int
}
