package config

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"
)

// docPath is the reference page this test writes and then guards.
const docPath = "../../docs/configuration.md"

var update = flag.Bool("update", false, "rewrite "+docPath+" from the struct")

// TestConfigurationReferenceIsCurrent renders docs/configuration.md from the
// Config struct and fails when the committed page says something else. With
// -update it writes the page instead, which is what `go generate
// ./internal/config/` runs.
//
// Generated rather than written because a reference table is the documentation
// that goes stale first: the variable gets added, the code works, and the table
// is a separate errand nobody has. Here the page is a build artefact of the
// struct, so the errand is a test failure.
func TestConfigurationReferenceIsCurrent(t *testing.T) {
	want, err := renderConfigurationDoc()
	if err != nil {
		t.Fatal(err)
	}
	if *update {
		// 0o644: it is documentation in a public repository.
		if err := os.WriteFile(docPath, want, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s, %d bytes", docPath, len(want))
		return
	}
	got, err := os.ReadFile(docPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s is stale. Run `go generate ./internal/config/` and commit the result.\n%s",
			docPath, firstDifference(got, want))
	}
}

// firstDifference names the line the two documents part company on, because a
// diff of the whole page in a test log is unreadable and the answer is always
// one line.
func firstDifference(got, want []byte) string {
	g, w := strings.Split(string(got), "\n"), strings.Split(string(want), "\n")
	for i := 0; i < len(g) && i < len(w); i++ {
		if g[i] != w[i] {
			return fmt.Sprintf("line %d:\n  committed: %s\n  generated: %s", i+1, g[i], w[i])
		}
	}
	return fmt.Sprintf("the committed page has %d lines, the generated one %d", len(g), len(w))
}

const docPreamble = `# Configuration

Every setting is an environment variable. ` + "`config.FromEnv`" + ` is the only
place that reads them, and it refuses on start what cannot work: two backup
targets, a bucket with no region or no credentials, an interval under a minute, a
prefix that would need escaping in a signed URL.

The defaults below are what the process uses when the variable is unset. To see
what one process actually read, ask it:

` + "```bash" + `
kanban doctor
` + "```" + `
`

// renderConfigurationDoc builds the page. The layout follows the struct: a blank
// line between fields starts a new table, and a comment above a group becomes the
// sentence in front of it, so the page is grouped the way somebody reading the
// source would group it.
func renderConfigurationDoc() ([]byte, error) {
	fields, err := configFields()
	if err != nil {
		return nil, err
	}
	defaults, err := configDefaults()
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	b.WriteString("<!-- Generated by `go generate ./internal/config/`. Edit the tags and the\n")
	b.WriteString("     comments on Config in internal/config/config.go, not this file. -->\n\n")
	b.WriteString(docPreamble)

	for _, group := range fields {
		b.WriteString("\n")
		if group.lead != "" {
			b.WriteString(group.lead + "\n\n")
		}
		b.WriteString("| Variable | Default | Notes |\n")
		b.WriteString("|---|---|---|\n")
		for _, f := range group.fields {
			def, ok := defaults[f.name]
			if !ok {
				return nil, fmt.Errorf("%s is tagged on the struct and FromEnv produces no value for it", f.name)
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", f.name, def, f.note)
		}
	}
	return []byte(b.String()), nil
}

type docField struct {
	name string // the environment variable
	note string // the trailing comment, plus what the secret tag implies
}

type docGroup struct {
	lead   string // the comment above the group, if it has one
	fields []docField
}

// configFields reads config.go rather than reflect.TypeOf(Config{}), because the
// prose worth publishing is in the comments and only the source has those.
func configFields() ([]docGroup, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "config.go", nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	var st *ast.StructType
	ast.Inspect(file, func(n ast.Node) bool {
		spec, ok := n.(*ast.TypeSpec)
		if !ok || spec.Name.Name != "Config" {
			return true
		}
		st, _ = spec.Type.(*ast.StructType)
		return false
	})
	if st == nil {
		return nil, fmt.Errorf("config.go has no Config struct")
	}

	var groups []docGroup
	current := docGroup{}
	prevEnd := 0
	for _, field := range st.Fields.List {
		start := fset.Position(field.Pos()).Line
		if field.Doc != nil {
			start = fset.Position(field.Doc.Pos()).Line
		}
		// A blank line in the struct, or a comment introducing a group, starts a
		// new table. The first field starts the first one.
		if len(current.fields) > 0 && (start-prevEnd > 1 || field.Doc != nil) {
			groups = append(groups, current)
			current = docGroup{}
		}
		if field.Doc != nil {
			lead, err := sentences(field.Doc)
			if err != nil {
				return nil, err
			}
			current.lead = lead
		}
		prevEnd = fset.Position(field.End()).Line

		if len(field.Names) != 1 {
			return nil, fmt.Errorf("line %d: one name per field, so a tag cannot be shared", start)
		}
		tag := reflect.StructTag(strings.Trim(fieldTag(field), "`"))
		name, ok := tag.Lookup("env")
		if !ok {
			continue
		}
		note := ""
		if field.Comment != nil {
			note, err = sentences(field.Comment)
			if err != nil {
				return nil, err
			}
		}
		switch tag.Get("secret") {
		case "true":
			note = join(note, "a secret: reports say `[set]` and never the value")
		case "url":
			note = join(note, "a secret: reports keep the address and take out the password")
		}
		current.fields = append(current.fields, docField{name: name, note: note})
	}
	if len(current.fields) > 0 {
		groups = append(groups, current)
	}
	return groups, nil
}

func fieldTag(field *ast.Field) string {
	if field.Tag == nil {
		return ""
	}
	return field.Tag.Value
}

// sentences flattens a comment group into one line of markdown. A comment that
// wraps in the source is one sentence on the page.
func sentences(c *ast.CommentGroup) (string, error) {
	text := strings.Join(strings.Fields(c.Text()), " ")
	// The table separates cells with pipes, and a comment that contains one would
	// split the row.
	return linkADRs(strings.ReplaceAll(text, "|", `\|`))
}

// adrRef finds a bare reference to a decision record. The number is the stable
// part of the file name and the slug is not, so the number is what a comment
// carries.
var adrRef = regexp.MustCompile(`docs/adr/(\d{4})`)

// linkADRs turns those references into links, so a comment that reads well in the
// source is navigable on the page.
func linkADRs(text string) (string, error) {
	var err error
	out := adrRef.ReplaceAllStringFunc(text, func(match string) string {
		number := adrRef.FindStringSubmatch(match)[1]
		found, globErr := filepath.Glob("../../docs/adr/" + number + "-*.md")
		switch {
		case globErr != nil:
			err = globErr
		case len(found) != 1:
			err = fmt.Errorf("docs/adr/%s: %d files match it, want one", number, len(found))
		default:
			// The generated page lives in docs/, so the link is relative to that.
			return fmt.Sprintf("[%s](adr/%s)", match, filepath.Base(found[0]))
		}
		return match
	})
	return out, err
}

func join(a, b string) string {
	if a == "" {
		return b
	}
	return strings.TrimSuffix(a, ".") + "; " + b
}

// configDefaults is what each variable is worth when none of them is set. The
// raw struct is read rather than Settings(), because Settings() masks the
// secrets and a table of defaults that says `[set]` answers nothing.
func configDefaults() (map[string]string, error) {
	cfg, err := FromEnv(func(string) string { return "" })
	if err != nil {
		return nil, fmt.Errorf("the defaults do not validate: %w", err)
	}
	rv := reflect.ValueOf(cfg)
	rt := rv.Type()
	out := map[string]string{}
	for i := range rt.NumField() {
		name, ok := rt.Field(i).Tag.Lookup("env")
		if !ok {
			continue
		}
		value := settingValue(rv.Field(i))
		if d, isDuration := rv.Field(i).Interface().(time.Duration); isDuration {
			value = wholeHours(d)
		}
		if value == "" {
			out[name] = "*(unset)*"
			continue
		}
		out[name] = "`" + value + "`"
	}
	return out, nil
}

// wholeHours prints a duration the way somebody would type it. Duration.String()
// spells a day `24h0m0s`, and this page is read by whoever is deciding what to
// put in the variable.
func wholeHours(d time.Duration) string {
	if d != 0 && d%time.Hour == 0 {
		return strconv.FormatInt(int64(d/time.Hour), 10) + "h"
	}
	return d.String()
}

// The readme is where people look first, so it gets the same treatment: every
// variable has to appear in it, and it must not offer one that does not exist.
func TestReadmeMentionsEveryVariable(t *testing.T) {
	body, err := os.ReadFile("../../readme.md")
	if err != nil {
		t.Fatal(err)
	}
	block, err := envBlock(string(body))
	if err != nil {
		t.Fatal(err)
	}
	cfg, err := FromEnv(func(string) string { return "" })
	if err != nil {
		t.Fatal(err)
	}
	known := map[string]bool{}
	for _, s := range cfg.Settings() {
		known[s.Name] = true
		// Mentioned counts: LISTEN_ADDR earns its place in the comment on
		// SERVER_PORT rather than a line of its own.
		if !strings.Contains(block, s.Name) {
			t.Errorf("the readme's environment block does not mention %s", s.Name)
		}
	}
	known["AWS_REGION"] = true // the fallback for BACKUP_S3_REGION
	for _, name := range submatches(regexp.MustCompile(`(?m)^([A-Z][A-Z0-9_]*)=`), []byte(block)) {
		if !known[name] {
			t.Errorf("the readme's environment block offers %s, which no field of Config reads", name)
		}
	}
}

// envBlock returns the fenced block under the readme's Environment Variables
// heading.
func envBlock(readme string) (string, error) {
	_, rest, ok := strings.Cut(readme, "### Environment Variables")
	if !ok {
		return "", fmt.Errorf("the readme has no Environment Variables section")
	}
	_, rest, ok = strings.Cut(rest, "```")
	if !ok {
		return "", fmt.Errorf("the Environment Variables section has no block")
	}
	block, _, ok := strings.Cut(rest, "```")
	if !ok {
		return "", fmt.Errorf("the block under Environment Variables is not closed")
	}
	return block, nil
}
